# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1402, 844)
        Form.setStyleSheet("\n"
"QToolTip{background: #191c22; color:white; border:1px solid #5a616f}"
                           """QMessageBox {
        background-color: #191c22;
		border:1px solid white;}
		QMessageBox QLabel {
        color: #aaa;}
        QMessageBox QPushButton{
        background: #191c22;
        color:white;
        
        }
        QPushButton::hover{
        background-color: rgb(0, 208, 255);
        }
        QPushButton::pressed{
        background-color: rgba(0, 208, 255, 200);
        }
        
		""")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.container = QtWidgets.QFrame(Form)
        self.container.setStyleSheet("QFrame#container{\n"
"background-color: rgb(243, 243, 243);\n"
"border:2px solid rgb(0, 208, 255);\n"
"}\n"
"\n"
"")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.gridLayout = QtWidgets.QGridLayout(self.container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_4 = QtWidgets.QFrame(self.container)
        self.frame_4.setStyleSheet("border:0px;\n"
"background-color: rgb(40, 44, 54);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setContentsMargins(30, 30, 30, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textContainer = QtWidgets.QFrame(self.frame_4)
        self.textContainer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:1px solid black; \n"
"border-bottom:0px;")
        self.textContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textContainer.setObjectName("textContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.textContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textLayout = QtWidgets.QVBoxLayout()
        self.textLayout.setObjectName("textLayout")
        self.frame = QtWidgets.QFrame(self.textContainer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textLayout.addWidget(self.frame)
        self.verticalLayout_5.addLayout(self.textLayout)
        self.gridLayout_2.addWidget(self.textContainer, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.settingsLbl = QtWidgets.QLabel(self.groupBox)
        self.settingsLbl.setMinimumSize(QtCore.QSize(0, 0))
        self.settingsLbl.setMaximumSize(QtCore.QSize(16777215, 45))
        self.settingsLbl.setStyleSheet("font: 8pt \"Yu Gothic UI\";\n"
"background-color: rgb(40, 44, 54);\n"
"color: rgb(0, 208, 255);\n"
"border-top:1px solid black; \n"
"border-right:1px solid black; ")
        self.settingsLbl.setWordWrap(True)
        self.settingsLbl.setObjectName("settingsLbl")
        self.horizontalLayout_3.addWidget(self.settingsLbl)
        self.openBtn = QtWidgets.QPushButton(self.groupBox)
        self.openBtn.setMinimumSize(QtCore.QSize(60, 0))
        self.openBtn.setMaximumSize(QtCore.QSize(60, 45))
        self.openBtn.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #191c22;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgba(0, 208, 255, 200);\n"
"}\n"
"")
        self.openBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/text/icons/commandline_532ik8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openBtn.setIcon(icon)
        self.openBtn.setIconSize(QtCore.QSize(24, 24))
        self.openBtn.setObjectName("openBtn")
        self.horizontalLayout_3.addWidget(self.openBtn)
        self.clearTextBtn = QtWidgets.QPushButton(self.groupBox)
        self.clearTextBtn.setMinimumSize(QtCore.QSize(60, 0))
        self.clearTextBtn.setMaximumSize(QtCore.QSize(60, 45))
        self.clearTextBtn.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #191c22;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgba(0, 208, 255, 200);\n"
"}\n"
"")
        self.clearTextBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/icons/4115230-cancel-close-cross-delete_11404ö8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearTextBtn.setIcon(icon1)
        self.clearTextBtn.setIconSize(QtCore.QSize(25, 25))
        self.clearTextBtn.setObjectName("clearTextBtn")
        self.horizontalLayout_3.addWidget(self.clearTextBtn)
        self.saveBtn = QtWidgets.QPushButton(self.groupBox)
        self.saveBtn.setMinimumSize(QtCore.QSize(60, 45))
        self.saveBtn.setMaximumSize(QtCore.QSize(60, 45))
        self.saveBtn.setStyleSheet("QPushButton{\n"
"border-right:1px solid black; \n"
"    background-color: #191c22;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgba(0, 208, 255, 200);\n"
"}\n"
"")
        self.saveBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/text/icons/1490129349-rounded05_821d90l.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBtn.setIcon(icon2)
        self.saveBtn.setIconSize(QtCore.QSize(44, 44))
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_3.addWidget(self.saveBtn)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_4, 1, 2, 1, 1)
        self.menuBar = QtWidgets.QFrame(self.container)
        self.menuBar.setStyleSheet("QFrame#menuBar{\n"
"background-color: #0f1014;\n"
"border:0px;\n"
"}")
        self.menuBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menuBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuBar.setObjectName("menuBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menuBar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.appName = QtWidgets.QLabel(self.menuBar)
        self.appName.setStyleSheet("font: 11pt \"Yu Gothic UI\";\n"
"color:white;")
        self.appName.setObjectName("appName")
        self.horizontalLayout_2.addWidget(self.appName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.minBtn = QtWidgets.QPushButton(self.menuBar)
        self.minBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.minBtn.setMaximumSize(QtCore.QSize(45, 35))
        self.minBtn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgba(0, 208, 255, 200);\n"
"}\n"
"")
        self.minBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/menu/icons/4115236-delete-min-minus_11j4d026.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn.setIcon(icon3)
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_2.addWidget(self.minBtn)
        self.restoreBtn = QtWidgets.QPushButton(self.menuBar)
        self.restoreBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.restoreBtn.setMaximumSize(QtCore.QSize(45, 35))
        self.restoreBtn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"QPushButton::checked{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"")
        self.restoreBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/menu/icons/window_maximGize_icon_181ö22d8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreBtn.setIcon(icon4)
        self.restoreBtn.setCheckable(True)
        self.restoreBtn.setObjectName("restoreBtn")
        self.horizontalLayout_2.addWidget(self.restoreBtn)
        self.exitBtn = QtWidgets.QPushButton(self.menuBar)
        self.exitBtn.setMinimumSize(QtCore.QSize(45, 35))
        self.exitBtn.setMaximumSize(QtCore.QSize(45, 35))
        self.exitBtn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgba(0, 208, 255, 200);\n"
"}\n"
"")
        self.exitBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/menu/icons/4115230-cancel-close-cross-delete_11404ö8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon5)
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_2.addWidget(self.exitBtn)
        self.gridLayout.addWidget(self.menuBar, 0, 1, 1, 2)
        self.logoFrame = QtWidgets.QFrame(self.container)
        self.logoFrame.setMinimumSize(QtCore.QSize(45, 35))
        self.logoFrame.setMaximumSize(QtCore.QSize(45, 35))
        self.logoFrame.setStyleSheet("background-color: #0f1014;\n"
"")
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.logoFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QPushButton(self.logoFrame)
        self.logo.setEnabled(False)
        self.logo.setMinimumSize(QtCore.QSize(45, 35))
        self.logo.setMaximumSize(QtCore.QSize(45, 35))
        self.logo.setStyleSheet("border-bottom:1px solid rgb(213, 213, 213)")
        self.logo.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/logo/icons/brand_python_icon_1w5s7f826.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo.setIcon(icon6)
        self.logo.setIconSize(QtCore.QSize(32, 32))
        self.logo.setFlat(True)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.gridLayout.addWidget(self.logoFrame, 0, 0, 1, 1)
        self.navBar = QtWidgets.QFrame(self.container)
        self.navBar.setStyleSheet("QFrame{\n"
"background-color: #0f1014;\n"
"border:0px;\n"
"}")
        self.navBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navBar.setObjectName("navBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.expandBtn = QtWidgets.QPushButton(self.navBar)
        self.expandBtn.setMinimumSize(QtCore.QSize(45, 45))
        self.expandBtn.setMaximumSize(QtCore.QSize(45, 45))
        self.expandBtn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"width:10;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(40, 44, 54);\n"
"}\n"
"QPushButton::checked{\n"
"background-color: #191c22;\n"
"}\n"
"")
        self.expandBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/nav/icons/burger_line_list_menu_nav_ndavigation_option_icon_123231.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.expandBtn.setIcon(icon7)
        self.expandBtn.setIconSize(QtCore.QSize(22, 22))
        self.expandBtn.setCheckable(True)
        self.expandBtn.setObjectName("expandBtn")
        self.verticalLayout_2.addWidget(self.expandBtn)
        self.painterBtn = QtWidgets.QPushButton(self.navBar)
        self.painterBtn.setMinimumSize(QtCore.QSize(45, 45))
        self.painterBtn.setMaximumSize(QtCore.QSize(45, 45))
        self.painterBtn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 208, 255);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgba(0, 208, 255, 200);\n"
"}\n"
"")
        self.painterBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/nav/icons/printer-printing-a-picture-of-a-landscape_icon-icons.com_56236.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.painterBtn.setIcon(icon8)
        self.painterBtn.setIconSize(QtCore.QSize(24, 24))
        self.painterBtn.setObjectName("painterBtn")
        self.verticalLayout_2.addWidget(self.painterBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.settingBtn = QtWidgets.QPushButton(self.navBar)
        self.settingBtn.setMinimumSize(QtCore.QSize(45, 45))
        self.settingBtn.setMaximumSize(QtCore.QSize(45, 45))
        self.settingBtn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"width:10;\n"
"}\n"
"QPushButton::hover{\n"
"background-color: #191c22;\n"
"}\n"
"QPushButton::checked{\n"
"\n"
"background-color: rgb(40, 44, 54);\n"
"}")
        self.settingBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/nav/icons/settings_icon-icons.com_49858l.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingBtn.setIcon(icon9)
        self.settingBtn.setIconSize(QtCore.QSize(24, 24))
        self.settingBtn.setCheckable(True)
        self.settingBtn.setChecked(True)
        self.settingBtn.setObjectName("settingBtn")
        self.verticalLayout_2.addWidget(self.settingBtn)
        self.gridLayout.addWidget(self.navBar, 1, 0, 1, 1)
        self.optionBar = QtWidgets.QFrame(self.container)
        self.optionBar.setMinimumSize(QtCore.QSize(0, 0))
        self.optionBar.setMaximumSize(QtCore.QSize(0, 16777215))
        self.optionBar.setStyleSheet("QFrame{background: #191c22;\n"
"border:0px;}\n"
"\n"
"QScrollBar:horizontal\n"
"    {\n"
"        height: 15px;\n"
"        margin: 3px 15px 3px 15px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"        background-color: rgba(0, 0, 0,0);\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal\n"
"    {\n"
"         background-color: rgb(0, 230, 255);\n"
"        min-width: 5px;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal\n"
"    {\n"
"        margin: 0px 3px 0px 3px;\n"
"        border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"        width: 10px;\n"
"        height: 10px;\n"
"        subcontrol-position: right;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:horizontal\n"
"    {\n"
"        margin: 0px 3px 0px 3px;\n"
"        border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: left;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/right_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: right;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"\n"
"    QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/left_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: left;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"\n"
"    QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar:vertical\n"
"    {\n"
"         background-color: none;\n"
"        width: 15px;\n"
"        margin: 15px 3px 15px 3px;\n"
"        border: 1px transparent #2A2929;\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical\n"
"    {\n"
"        background-color: rgb(0, 230, 255);\n"
"        min-height: 5px;\n"
"\n"
"        border-radius: 4px;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical\n"
"    {\n"
"        margin: 3px 0px 3px 0px;\n"
"        border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: top;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"    {\n"
"        border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"        height: 10px;\n"
"        width: 10px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"    {\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"    {\n"
"        background: none;\n"
"    }")
        self.optionBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.optionBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.optionBar.setObjectName("optionBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.optionBar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.optionBar)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border:0px;\n"
"background: #191c22;\n"
"border-bottom: 1px solid rgb(40, 44, 54);\n"
"    color: rgb(0, 230, 255);\n"
"    font: 350 10pt \"Yu Gothic UI Semilight\";\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.searchBtn = QtWidgets.QPushButton(self.optionBar)
        self.searchBtn.setMinimumSize(QtCore.QSize(45, 45))
        self.searchBtn.setMaximumSize(QtCore.QSize(45, 45))
        self.searchBtn.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"width:10;\n"
"border-bottom: 1px solid rgb(40, 44, 54);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(40, 44, 54);\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: #191c22;\n"
"}\n"
"")
        self.searchBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/nav/icons/magnifying-sglass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchBtn.setIcon(icon10)
        self.searchBtn.setIconSize(QtCore.QSize(22, 22))
        self.searchBtn.setCheckable(True)
        self.searchBtn.setObjectName("searchBtn")
        self.gridLayout_3.addWidget(self.searchBtn, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.treeView = QtWidgets.QTreeView(self.optionBar)
        self.treeView.setStyleSheet("QTreeView{background: #191c22; color:white}\n"
"\n"
"QTreeView::item::hover{border-left:2px solid white; background:#5a616f}\n"
"QTreeView::item::selected{border-left:3px solid  rgb(0, 208, 255);color:white}\n"
"QTreeView::item {border-left: 1px solid #5a616f}")
        self.treeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeView.setDragEnabled(True)
        self.treeView.setDragDropOverwriteMode(True)
        self.treeView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.treeView)
        self.gridLayout.addWidget(self.optionBar, 1, 1, 1, 1)
        self.optionBar.raise_()
        self.navBar.raise_()
        self.menuBar.raise_()
        self.frame_4.raise_()
        self.logoFrame.raise_()
        self.horizontalLayout.addWidget(self.container)

        self.retranslateUi(Form)
        self.minBtn.clicked.connect(Form.showMinimized)
        self.exitBtn.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.settingsLbl.setText(_translate("Form", "CodeEditor"))
        self.openBtn.setToolTip(_translate("Form", "<html><head/><body><p>Prompt Ausgabe</p></body></html>"))
        self.clearTextBtn.setToolTip(_translate("Form", "<html><head/><body><p>Textfeld leeren</p></body></html>"))
        self.saveBtn.setToolTip(_translate("Form", "<html><head/><body><p>Inhalt Speichern</p></body></html>"))
        self.appName.setText(_translate("Form", "CodeEditor"))
        self.expandBtn.setToolTip(_translate("Form", "<html><head/><body><p>Navigation ein und ausblenden.</p></body></html>"))
        self.painterBtn.setToolTip(_translate("Form", "Drucken"))
        self.settingBtn.setToolTip(_translate("Form", "<html><head/><body><p>Navigation ein und ausblenden.</p></body></html>"))
        self.searchBtn.setToolTip(_translate("Form", "<html><head/><body><p>Ordner Durchsuchen</p></body></html>"))
import images.img
